name: Laravel (Darwin)

on:
  push:
    branches: [ "Darwin" ]
  pull_request:
    branches: [ "Darwin" ]

jobs:
  laravel-log:
    runs-on: ubuntu-latest

    steps:
      # Configurar PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Clonar el repositorio
      - uses: actions/checkout@v4

      # Copiar .env si no existe
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Instalar dependencias
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Generar clave de la aplicación
      - name: Generate key
        run: php artisan key:generate

      # Permisos necesarios
      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # Crear base de datos sqlite (si es necesario)
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      # Generar log de ejecución
      - name: Generate Execution Log
        run: |
          echo "=== GitHub Action Execution Log ===" > storage/logs/github_action.log
          echo "Date: $(date)" >> storage/logs/github_action.log
          echo "Branch: Darwin" >> storage/logs/github_action.log
          echo "Commit: $GITHUB_SHA" >> storage/logs/github_action.log
          echo "Executed by: $GITHUB_ACTOR" >> storage/logs/github_action.log
          echo "Repository: $GITHUB_REPOSITORY" >> storage/logs/github_action.log
          echo "===================================" >> storage/logs/github_action.log

      # Ejecutar pruebas de Laravel (opcional)
      - name: Run Laravel Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
